import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/footer";

const manname = localFont({
  src: "./fonts/Maname-Regular.ttf",
  variable: "--font-maname-reg",
  weight: "400",
});
const marcellus = localFont({
  src: "./fonts/Marcellus-Regular.ttf",
  variable: "--font-marcellus-reg",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${marcellus.variable} ${manname.variable} antialiased flex flex-col items-center`}
        >
          <header>
            <h1>Quick Think</h1>
          </header>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/About">About</Link>
            <SignedIn>
              <Link href="/UserProfile">User Profile</Link>
              <Link href="/Play">Play</Link>
            </SignedIn>
            <SignedOut>
              <SignInButton className={`${marcellus.variable} signIn`} />
            </SignedOut>
          </nav>

          <br />
          {children}

          <footer className="footer">
            <br />
            <Footer />
            <br />

            <UserButton className="signIn" />
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
