import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const manname = localFont({
  src: "./fonts/Maname-Regular.ttf",
  variable: "--font-maname-reg",
  weight: "400",
});
const marcellus = localFont({
  src: "./fonts/Marcellus-Regular.ttf",
  variable: "--font-marcellus-reg",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${marcellus.variable} ${manname.variable} antialiased`}
        >
          <header>
            <h1>Quick Think</h1>
          </header>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/About">About</Link>
          </nav>
          <br />
          <SignedOut>
            <SignInButton className={`${marcellus.variable} signIn`} />
          </SignedOut>
          <SignedIn>
            <nav>
              {/* <b> */}
              <Link href="/UserProfile">User Profile</Link>
              <Link href="/Play">Play</Link>
              {/* </b> */}
            </nav>
            <UserButton />
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
